name: test_actions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install required dependencies
          pip install -r requirements.txt
          
          # Run your ML training script
          python model.py
          
          # Create a report with model metrics
          echo "## Model Metrics" > report.md
          cat metrics.txt >> report.md
          
          # Send the report as a comment on the PR
          cml-send-comment report.md --repo ${{ github.repository }} --token ${{ secrets.GITHUB_TOKEN }}
